import Testing

@testable import AdventOfCode

// Make a copy of this file for every day to ensure the provided smoke tests
// pass.
struct Day08Tests {
  // Smoke test data provided in the challenge question
  let file = """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    """
  let calibrations: [(UInt64, [UInt64])] = [
  ]

  @Test func testPart1() async throws {
    let challenge = Day08(data: file)
    #expect(String(describing: challenge.part1()) == "14")
  }

  @Test func testPart2() async throws {
    let challenge = Day08(data: file)
    #expect(String(describing: challenge.part2()) == "34")
  }
}
